parameters:
  notifications.revenueThreshold: 100

services:
  _instanceof:
    Sparkrvp\SparkPlugins\SparkWoo\Common\Modules\ModuleInterface:
      tags: ["app.module"]
    Sparkrvp\SparkPlugins\SparkWoo\Common\Options\OptionInterface:
      tags: ["app.option"]
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      $pluginMeta: "@plugin-meta"
  dismissed-subscribe-notification-option:
    class: Sparkrvp\SparkPlugins\SparkWoo\Common\Options\BooleanOption
    arguments:
      $prefix: "%plugin.prefix%"
      $name: dismissed_subscribed_to_mail_list_free
  installed-timestamp-option:
    class: Sparkrvp\SparkPlugins\SparkWoo\Common\Options\StringOption
    arguments:
      $prefix: "%plugin.prefix%"
      $name: installed_timestamp
  Sparkrvp\SparkPlugins\SparkWoo\CommonFree\MailList\SubscribeToMailListModule:
    arguments:
      $notificationModule: '@Sparkrvp\SparkPlugins\SparkWoo\Common\Notifications\NotificationModule'
      $dismissedOption: "@dismissed-subscribe-notification-option"
      $installedTimestampOption: "@installed-timestamp-option"
